# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclicu < Formula
  desc "A blazing fast terminal UI for ClickUp."
  homepage "https://github.com/PeterJohnBishop/goclicu"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.2/goclicu_Darwin_x86_64.tar.gz"
      sha256 "8a0da65668090ec38224964bc59130583d5f65b3454f192c0336ae2da7b8c309"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.2/goclicu_Darwin_arm64.tar.gz"
      sha256 "91461605e39513a36a84c2f745734e147727778cad82e1cb1590f122ce4e34dd"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.2/goclicu_Linux_x86_64.tar.gz"
      sha256 "cc30d9e7758cc383cc2366319037052eed38238a6a4153b7bdee0abe6adec201"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.2/goclicu_Linux_arm64.tar.gz"
      sha256 "589aac2ffab29bb4b1ae7b0cd2b96a3e6a30551d56076f1891707bb954b2f8f9"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  test do
    system "#{bin}/goclicu --version"
  end
end
